# mgp.jl
# =============================================================================
# Model layer for the "one filter, many models" design.
#
#   A model is DATA: a list of events, each carrying a population transition,
#   a hazard, a production vector, an event type, and its deme wiring. The
#   generic KLI filter (mgp_filter.jl) consumes this data. NO likelihood math
#   lives here.
#
# STATUS: compiler-checked. The generated SEIR event table and hazard closures were
#   executed and compared with the explicit audit table below. Inspect
#   `@macroexpand @mgp Name ...` when auditing an additional model. The explicit
#   `SEIR_REFERENCE` table remains the row-by-row audit artifact; `SEIR` is
#   generated by `@mgp` and has been checked to match it.
#
# Primary source: King, Lin & Ionides, "Exact phylodynamic likelihood via
#   structured Markov genealogy processes" (StructuredMGPs.pdf). Section /
#   equation references below are to that paper.
# =============================================================================

export @mgp, @event, EventType, Event, MGPModel, SEIR, MERS

# -----------------------------------------------------------------------------
# Event types: the five PURE event types of KLI §3.2.
#   BIRTH     (a) branching of new lineages from a parent (e.g. transmission)
#   MIGRATION (c) a lineage moves between demes (e.g. infection progression)
#   DEATH     (b) extinction of lineages (e.g. recovery)      -> no coloring op
#   SAMPLE    (d) collection of a sample                      -> chop χ
#   NEUTRAL   (e) no change to any lineage (e.g. waning)
# Compound events (§3.2(f)) are out of scope for this scaffold.
# -----------------------------------------------------------------------------
@enum EventType BIRTH MIGRATION DEATH SAMPLE NEUTRAL

"""
    Event

One jump mark `u` of the population process, as it bears on the genealogy.

Fields
- `name`     : identifier.
- `Δ`        : population stoichiometry, e.g. `[:S=>-1, :E=>+1]`.
- `hazard`   : `(x, θ) -> Float64`, the population hazard αᵤ(t,x) (KLI §2.5).
- `r`        : production rᵘ, a PER-MARK CONSTANT (KLI §3.3.1; SEIRS values in
               Table 2). Indexed by deme.
- `type`     : one of the five pure `EventType`s (§3.2).
- `from`     : source deme index (birth parent / migration source); 0 = none.
- `into`     : child / target deme indices.
- `regular`  : true = regular (between genealogy events); false = singular
               (at ev(Z)).
- `observed` : true = can produce a genealogy feature; false = background.

Note: saturation `s` and lineage count `ℓ` are NOT stored here. Both depend on
the pruned genealogy at time t (`s = s(Yₜ)`, KLI §3.4.2) and are computed by the
filter at each event. The specific coloring operator (chop χ, swap σ, fork κ;
§5.1) is likewise derived at runtime from `type` and the local genealogy via the
compatibility indicator Qᵤ (Eq. 38) — one mark is generally compatible with
several coloring outcomes, so it cannot be a single stored operator.
"""
struct Event
    name     :: Symbol
    Δ        :: Vector{Pair{Symbol,Int}}
    hazard   :: Function
    r        :: Vector{Int}
    type     :: EventType
    from     :: Int
    into     :: Vector{Int}
    regular  :: Bool
    observed :: Bool
end

"""
    MGPModel

A model: its full compartment set, the deme subset that carries lineages
(the `Coloring` set — KLI §2.6, e.g. {E,I} ⊂ {S,E,I,R}), and its events.
"""
struct MGPModel
    name         :: Symbol
    compartments :: Vector{Symbol}
    demes        :: Vector{Symbol}
    events       :: Vector{Event}
end

# =============================================================================
# EXPLICIT SEIR MODEL — the audit target.
#
# This is what the macro must expand to. Check it row-by-row against KLI
# Table 2 (rᵘ and event type) and against seir_naive.jl. Demes are ordered
# (E, I): deme 1 = E, deme 2 = I, matching n(x) = (E, I) in §2.7.
# =============================================================================
const SEIR_REFERENCE = MGPModel(:SEIR, [:S, :E, :I, :R], [:E, :I], [
    # transmission: I parent sires an E child;  rᵘ=(1,1) BIRTH   (Table 2)
    Event(:infection,   [:S=>-1, :E=>+1], (x,θ)-> θ.β * x.S * x.I / θ.N,
          [1, 1], BIRTH,     2, [1],   true,  false),
    # progression: E → I lineage migration;      rᵘ=(0,1) MIGRATION (Table 2)
    Event(:progression, [:E=>-1, :I=>+1], (x,θ)-> θ.σ * x.E,
          [0, 1], MIGRATION, 1, [2],   true,  false),
    # recovery: pure death; no coloring op — enters decay only; rᵘ=(0,0)
    Event(:recovery,    [:I=>-1, :R=>+1], (x,θ)-> θ.γ * x.I,
          [0, 0], DEATH,     2, Int[], true,  false),
    # waning: neutral;                           rᵘ=(0,0)
    Event(:waning,      [:R=>-1, :S=>+1], (x,θ)-> θ.ω * x.R,
          [0, 0], NEUTRAL,   0, Int[], true,  false),
    # sampling: singular, observed; chop χ;      rᵘ=(0,1) SAMPLE (Table 2)
    Event(:sampling,    Pair{Symbol,Int}[], (x,θ)-> θ.ψ * x.I,
          [0, 1], SAMPLE,    2, Int[], false, true),
])

# =============================================================================
# @mgp turns the documented declarative move notation into an
# MGPModel identical to the explicit form above. It carries NO likelihood math:
# its only real job is rewriting bare model symbols in `rate=` into field
# accesses on the state/parameter NamedTuples.
#
# VERIFIED: the generated `SEIR` structural fields and hazard values match the
# explicit `SEIR_REFERENCE` table.
# =============================================================================

include("mgp_macro.jl")
include("mgp_mers.jl")
